# Generated by Django 3.1.6 on 2021-02-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_price', models.IntegerField()),
                ('hour_price', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
