# Generated by Django 3.1.6 on 2021-02-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='hour_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='head',
            name='trade_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='head',
            name='volume',
            field=models.FloatField(),
        ),
    ]
