# Generated by Django 3.1.6 on 2021-02-17 09:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210217_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about_image', models.ImageField(blank=True, upload_to='photos')),
                ('about_title', models.CharField(max_length=255)),
                ('about_description', ckeditor.fields.RichTextField()),
                ('market_captilization', models.FloatField(blank=True)),
                ('daily_transaction', models.FloatField(blank=True)),
                ('active_accounts', models.IntegerField(blank=True)),
                ('years', models.IntegerField(blank=True)),
            ],
        ),
    ]
