# Generated by Django 3.1.6 on 2021-02-20 04:11

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', ckeditor.fields.RichTextField()),
                ('article_photo', models.ImageField(blank=True, upload_to='photos')),
                ('article_description', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('no_of_comments', models.IntegerField()),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
    ]
